name: Bump version.json for build

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensures git log works in bump-version.js

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bump version.json
        run: node bump-version.js

      - name: Build
        run: npm run build
